version: "2"
services:
  app:
    container_name: xai-survey
    restart: always
    build: .
    environment:
      - REACT_APP_ATLAS_CONNECTION=mongodb://mongo:27017/xai_surveys
      - REACT_APP_PORT=3000
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
